create home page
git-0r/ecom pull request #1
Opened 2022-03-19 18:18 UTC by git-0r

# Home page for e-commerce
![ecom-home-1](https://user-images.githubusercontent.com/68228131/159133492-cd490fec-bf04-4779-a68a-9ff07b7eccd0.png)
![ecom-home-2](https://user-images.githubusercontent.com/68228131/159133496-be14ca0f-7ddc-47c3-9f01-bbeb5c819e50.png)
![ecom-home-3](https://user-images.githubusercontent.com/68228131/159133565-952fb966-2a6a-46be-acc9-03b6f25e0143.png)

2022-03-20 08:02 UTC, yaswanthmyneni approved these changes
The UI looks great, you can merge.

2022-03-20 08:02 UTC, yaswanthmyneni commented on src/pages/Home.js
> +import PopularCategory from "../components/PopularCategory";
suggestion: add index.js in components folder and export all components from it

2022-03-20 17:42 UTC, Naman-Saxena1 requested changes
Code looks fine.
I have 1 UI suggestion
![Capture3](https://user-images.githubusercontent.com/90456667/159175217-b5cc4521-10a7-4961-b544-529501f3e28f.PNG)

I believe bottle overflowing is intentional and that is fine.
But text is overflowing differently for different cards and looks strange for consistent UI design, so can do some alignment on it.

Everything else looks great 👍

2022-03-20 17:42 UTC, Naman-Saxena1 commented on src/components/Navbar.js
> +                <p>Blog</p>
I think for semantic HTML, it would be better to have them as buttons rather than p tag.

2022-03-21 09:01 UTC, Naman-Saxena1 approved these changes

2022-03-21 09:17 UTC, merged